run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # complexity
    - maintidx
    - funlen

    # disable
    - cyclop
    - depguard
    - err113
    - execinquery
    - exhaustruct
    - gocognit
    - gomnd
    - ireturn
    - lll
    - mnd
    - perfsprint
    - prealloc
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/SecurityBrewery/catalyst-analysis)